name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platforms:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - host: macos-latest
            target: aarch64-apple-darwin
    name: Build ${{ matrix.platforms.target }}
    runs-on: ${{ matrix.platforms.host }}
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@f16df2948c720c72059633eed723bbf5b3719ae2 # use-mise-action-v1.2.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
          targets: ${{ matrix.platforms.target }}
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build --target ${{ matrix.platforms.target }} --release
      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: bindings-${{ matrix.platforms.target }}
          path: ${{ matrix.platforms.target == 'x86_64-unknown-linux-gnu' && 'dist/' || 'dist/*.node' }}
          if-no-files-found: error

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@f16df2948c720c72059633eed723bbf5b3719ae2 # use-mise-action-v1.2.0

      - name: Download all artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          path: artifacts

      - name: Assemble dist
        run: mkdir -p dist && cp artifacts/bindings-*/* dist/

      - name: List dist contents
        run: ls -R ./dist

      - name: Publish
        run: pnpm publish --access public --provenance --no-git-checks
